In [1]:
import pandas as pd
import pickle
import numpy as np
import torch
from torch import nn
import os 
import fastai
import fastai
from fastai.text import *
PATH="/home/kirana/Documents/phd/final"
DATAPATH="/home/kirana/Documents/phd/data/aclImdb"

## Dataset

In [2]:
[df_train,df_valid,df_test,itos, train_tokens, valid_tokens, test_tokens, trn_lm, val_lm, test_lm]=pickle.load(open(f'{PATH}/inter/dfs_tokens_fastai.pkl','rb'))

In [3]:
bs=52 # 52 - Jeremey, 20 - default

In [4]:
bptt= 70 #70 - Jeremey, 35 - default

In [5]:
def create_data_lm(tokens,bs):
    import itertools
    # Collapse into a single large array
    tokens=np.asarray(list (itertools.chain(*tokens)))
    # How many batches
    n_batch=len(tokens)//bs
    # Truncate to exclude the ones at the end
    tokens=tokens[:bs*n_batch]
    # Reshape
    tokens=tokens.reshape(bs,-1)
    return tokens

In [6]:
train_tokens=create_data_lm(df_train['tokens'],bs)
valid_tokens=create_data_lm(df_valid['tokens'],bs)
test_tokens=create_data_lm(df_test['tokens'],bs)
train_tokens.shape, valid_tokens.shape, test_tokens.shape

((52, 396650), (52, 43895), (52, 143259))

In [7]:
def get_batch(source, i):
    seq_len = min(args.bptt, len(source) - 1 - i)
    data = source[i:i+seq_len]
    target = source[i+1:i+1+seq_len].view(-1)
    return data, target

In [8]:
n_batch=train_tokens.shape[1]
for i in range(0,n_batch,bptt):
    seq_len=min(bptt,n_batch-1-i)
    x=train_tokens[:,i:i+seq_len]
    y=train_tokens[:,i+1:i+1+seq_len]
    print (x.shape, y.shape)
    break

(52, 70) (52, 70)


In [9]:
x.shape,y.shape

((52, 70), (52, 70))

In [10]:
x,y

(array([[   41,    42,    43,    40, ...,     2,  1896,   463,     4],
        [ 1071,    23,    67,    39, ...,     2,    98,    11,    63],
        [   54,    34,     7,   190, ...,     2,    87,    34,  5998],
        [    7,  1213,     8,   453, ...,   406,     4,     2,    46],
        ...,
        [   60,   126,   931,     6, ...,   114,    39,   599,    63],
        [    2, 15094,   132,    65, ...,    56,  1350,   209,   281],
        [11783,   658,   318,     3, ...,     6,    64,    79,  1268],
        [   42,    43,    40,     2, ...,   708,   111,     4,     2]]),
 array([[   42,    43,    40,    13, ...,  1896,   463,     4,     2],
        [   23,    67,    39,    18, ...,    98,    11,    63,    28],
        [   34,     7,   190,  1732, ...,    87,    34,  5998,    47],
        [ 1213,     8,   453,    21, ...,     4,     2,    46,     7],
        ...,
        [  126,   931,     6,   126, ...,    39,   599,    63,   314],
        [15094,   132,    65,   411, ...,  1350, 

In [11]:
x.shape,y.shape

((52, 70), (52, 70))

In [12]:
train_tokens.shape

(52, 396650)

## pre-trained AWD-LSTM

In [13]:
PATH_AWD_LSTM='/home/kirana/Documents/phd/data/pre-trained/awd_lstm/'

In [14]:
ls {PATH_AWD_LSTM}

bwd_wt103_enc.h5  fwd_wt103_enc.h5  itos_wt103.pkl  wt103_60002/
bwd_wt103.h5      fwd_wt103.h5      wt103_238642/   wt103_tiny.tgz


In [15]:
wgts = torch.load(f'{PATH_AWD_LSTM}/fwd_wt103.h5', map_location=lambda storage, loc: storage)

In [16]:
wgts

OrderedDict([('0.encoder.weight',
              tensor([[-1.2274e-01,  2.7886e-01, -3.8850e-01,  ..., -1.0404e-01,
                        1.9580e-02,  1.8548e-01],
                      [ 1.4854e-05, -2.3424e-05,  1.9693e-05,  ...,  2.1349e-05,
                        2.1776e-05, -1.2394e-05],
                      [ 1.8070e-01,  1.5874e+00, -1.1738e-01,  ..., -4.5935e-02,
                       -8.1352e-02,  1.8054e-01],
                      ...,
                      [-1.8595e-03, -6.8529e-03,  1.6999e-03,  ...,  1.7039e-03,
                        4.1632e-03, -1.3171e-03],
                      [-2.3120e-03, -6.9001e-03,  1.8772e-03,  ...,  5.0309e-04,
                        4.6596e-03, -2.5850e-03],
                      [-2.2463e-03, -9.1512e-03,  1.3927e-03,  ...,  1.2296e-03,
                        5.8085e-03, -1.8940e-03]])),
             ('0.encoder_with_dropout.embed.weight',
              tensor([[-1.2274e-01,  2.7886e-01, -3.8850e-01,  ..., -1.0404e-01,
                

In [17]:
wgts = torch.load(f'{PATH_AWD_LSTM}/fwd_wt103_enc.h5', map_location=lambda storage, loc: storage)

In [18]:
wgts

OrderedDict([('encoder.weight',
              tensor([[-1.2274e-01,  2.7886e-01, -3.8850e-01,  ..., -1.0404e-01,
                        1.9580e-02,  1.8548e-01],
                      [ 1.4854e-05, -2.3424e-05,  1.9693e-05,  ...,  2.1349e-05,
                        2.1776e-05, -1.2394e-05],
                      [ 1.8070e-01,  1.5874e+00, -1.1738e-01,  ..., -4.5935e-02,
                       -8.1352e-02,  1.8054e-01],
                      ...,
                      [-1.8595e-03, -6.8529e-03,  1.6999e-03,  ...,  1.7039e-03,
                        4.1632e-03, -1.3171e-03],
                      [-2.3120e-03, -6.9001e-03,  1.8772e-03,  ...,  5.0309e-04,
                        4.6596e-03, -2.5850e-03],
                      [-2.2463e-03, -9.1512e-03,  1.3927e-03,  ...,  1.2296e-03,
                        5.8085e-03, -1.8940e-03]])),
             ('encoder_with_dropout.embed.weight',
              tensor([[-1.2274e-01,  2.7886e-01, -3.8850e-01,  ..., -1.0404e-01,
                    

In [19]:
itos2=pickle.load(open(f'{PATH_AWD_LSTM}/itos_wt103.pkl','rb'))
stoi2 = collections.defaultdict(lambda: -1, { v: k for k, v in enumerate(itos2) })

In [20]:
wgts['encoder.weight'].shape

torch.Size([238462, 400])

In [21]:
enc_wgts = wgts['encoder.weight'].numpy() # converts np.ndarray from torch.FloatTensor.output shape: (238462, 400)
row_m = enc_wgts.mean(0) # returns the average of the array elements along axis 0. output shape: (400,)

In [22]:
enc_wgts.shape, len(itos)

((238462, 400), 59972)

In [23]:
n_emb=enc_wgts.shape[1]

In [24]:
new_w = np.zeros((len(itos),n_emb), dtype=np.float32) # shape: (60002, 400)

for i, w in enumerate(itos):
    r = stoi2[w]
    new_w[i] = enc_wgts[r] if r >= 0 else row_m

In [25]:
len(set(itos).difference(set(itos2)))

8910

## Model Architecture

In [27]:
from torch import nn
import torch
from torch.autograd import Variable

In [28]:
n_inp=len(itos)
n_emb=400 #650
n_hidden=400 #650
n_layers=2
dropout=0.5
wd=1e-7

In [29]:
class language_model (nn.Module):
    def __init__(self,n_inp,n_emb,n_hidden,n_layers,bidirectional,bs,device,dropout_e=0.05,dropout=0.5,\
                 dropout_o=0.5,pretrain_mtx=None,adaptive_log_softmax=True,tie_weights=True):
        super().__init__()
        self.n_inp,self.n_emb,self.n_hidden,self.n_layers,self.bidirectional,self.bs,self.device,self.pretrain_mtx=\
                            n_inp,n_emb,n_hidden,n_layers,bidirectional,bs,device,pretrain_mtx
        self.adaptive_log_softmax,self.tie_weights=adaptive_log_softmax,tie_weights
        self.dropout_e,self.dropout,self.dropout_o=dropout_e,dropout,dropout_o
        self.gen_hidden()
        self.create_architecture()
        if pretrain_mtx is not None:
            print ("initializing")
            self.initialize_glove()
            
        if self.adaptive_log_softmax is False:
            self.criterion=nn.CrossEntropyLoss()
        
    def create_architecture(self):
        # Dropout layer
        self.dropout_enc=nn.Dropout(self.dropout_e)
        # Embedding Layer
        self.encoder=nn.Embedding(self.n_inp,self.n_emb)
        # LSTM Layer
        self.lstm=nn.LSTM(self.n_emb,self.n_hidden,self.n_layers,batch_first=True,dropout=self.dropout,\
                          bidirectional=False)
        self.dropout_op=nn.Dropout(self.dropout_o)
        
        if self.adaptive_log_softmax:
            # Adaptive Log Softmax Loss
            self.adaptive_softmax=AdaptiveLogSoftmaxWithLoss(self.n_hidden,
                                    self.n_inp,
                                    cutoffs=[round(self.n_inp/15),3*round(self.n_inp/15)],
                                    div_value=4,
                                    get_full_prob=True)
        else:
            self.decoder=nn.Linear(self.n_hidden,self.n_inp)
    
    def freeze_embedding(self):
        self.encoder.weight.requires_grad=False
        if self.tie_weights:
            self.decoder.weight.requires_grad=False
        
    
    def unfreeze_embedding(self):
        self.encoder.weight.requires_grad=True
        if self.tie_weights:
            self.decoder.weight.requires_grad=True
        
    def initialize_glove(self):
        self.encoder.weight.data=torch.Tensor(self.pretrain_mtx)
        if self.tie_weights:
            self.decoder.weight=self.encoder.weight
    
    def gen_hidden(self):
        # Initialize hidden
        self.hidden=(Variable(torch.zeros(self.n_layers,self.bs,self.n_hidden,requires_grad=False).to(self.device)),
                     Variable(torch.zeros(self.n_layers,self.bs,self.n_hidden,requires_grad=False).to(self.device)))
    
        
    def forward(self,Xb,Yb):
        #import pdb
        #pdb.set_trace()
        embs=self.dropout_enc(self.encoder(Xb))
        if Xb.size(0) < self.bs:
            self.hidden=(self.hidden[0][:,:Xb.size(0),:].contiguous(),
            self.hidden[1][:,:Xb.size(0),:].contiguous())
        out,new_hidden=self.lstm(embs,self.hidden)
        out=self.dropout_op(out)
         # Wrap the hidden state in a new tensor without the gradients
        self.hidden=(Variable(new_hidden[0].data,requires_grad=False).to(self.device),\
                     Variable(new_hidden[1].data,requires_grad=False).to(self.device))
        if self.adaptive_log_softmax:
            out=out.reshape(out.size(0)*out.size(1),out.size(2))        # output is of shape n_batch * n_seq * n_hidden
      
            out=self.adaptive_softmax(out,Yb.view(-1))
            loss=out.loss
            preds=out.output_full
        else:
            #import pdb
            #pdb.set_trace()
            preds=self.decoder(out.contiguous().view(out.size(0)*out.size(1), out.size(2)))
            loss=self.criterion(preds,Yb.contiguous().view(-1))

        return preds, loss  

In [30]:
def accuracy_multinomial(preds,actual):
    preds=preds.max(1)[1]
    correct=preds==actual
    return correct.float().sum()/len(correct)

In [31]:
device="cuda:0"
model=language_model(n_inp,n_emb,n_hidden,n_layers,False,bs,device,0.05,0.5,0.5,new_w,False,True)


initializing


In [32]:
new_w.shape

(59972, 400)

In [33]:
model.encoder.weight.data.shape,model.decoder.weight.data.shape

(torch.Size([59972, 400]), torch.Size([59972, 400]))

In [34]:
nn.Linear(n_hidden,n_inp).weight.data.shape, n_hidden, n_inp

(torch.Size([59972, 400]), 400, 59972)

### Test if model forward works

In [35]:
model.decoder.weight.shape,model.encoder.weight.shape

(torch.Size([59972, 400]), torch.Size([59972, 400]))

In [36]:
x.shape

(52, 70)

In [37]:
if 1==0:
    model.forward(torch.LongTensor(x),torch.LongTensor(y))

In [38]:

model=model.to(device)

## Learner

In [39]:
class Learner():
    def __init__(self,model,optimizer,metric_fn,device,bptt=12,print_every=5,clip_val=None):
        self.model,self.optimizer,self.metric_fn,self.device,self.print_every,self.bptt,self.losses,self.clip_val=\
            model,optimizer,metric_fn,device,print_every,bptt,[],clip_val
        self.n_epochs=1

    
    def fit (self,Xb,Yb,mode_train=True):
        if mode_train:
            self.model.train()
        else:
            self.model.eval()
            
        preds,loss=self.model(Xb,Yb)
        
       
            
        
        with torch.no_grad():
            acc=self.metric_fn(preds,Yb.view(-1))
            acc=acc.item()
            del preds
        
        if mode_train:
            self.optimizer.zero_grad()
            loss.backward()
            self.optimizer.step()
        myloss=loss.item()
        del loss
        
        if self.clip_val is not None:
            torch.nn.utils.clip_grad_norm_(self.model.parameters(), 0.25)
            if 1==0:
                for p in self.model.parameters():
                    p.data.add_(self.lr, p.grad.data)
        
        return myloss, acc
    
    def lr_find (self,start_lr,end_lr,iterator,n_batch):
        losses,lrs=[],[]
        ratio=end_lr/start_lr
        num_steps=n_batch
        lr=start_lr
        for i in range(num_steps):            
            lr=lr*(end_lr/start_lr)**(1/num_steps)
            lrs.append(lr)
        self.lrs=lrs
        self.run_epoch(iterator,mode_train=True,lrs=lrs)
    
    def run_epoch(self,iterator,mode_train,lrs=None):
        n_batch=iterator.shape[1]
        epoch_loss,epoch_acc,i,k=0,0,0,0
        self.model.gen_hidden()
        #for k,i in enumerate(range(0,n_batch,self.bptt)):
        n_batch=iterator.shape[1]
        while i<n_batch-bptt:
            if mode_train:
                cust_bptt=self.bptt if np.random.random() < 0.95 else self.bptt//np.random.randint (2,4)
            else:
                cust_bptt=bptt
            seq_len=min(cust_bptt,n_batch-1-i)
            Xb=train_tokens[:,i:i+seq_len]
            Yb=train_tokens[:,i+1:i+1+seq_len]
            Xb=torch.LongTensor(Xb)
            Yb=torch.LongTensor(Yb)
            Xb=Xb.to(self.device)
            Yb=Yb.to(self.device)
            
            if lrs is not None:
                lr=lrs[k]
                for param_group in self.optimizer.param_groups:
                    param_group['lr']=lr 
            

            loss,acc=self.fit(Xb,Yb,mode_train)
            
            if lrs is not None:
                self.losses.append(loss)
            
            
            epoch_loss+=loss
            epoch_acc+=acc
            if k%self.print_every == 0:
                if k:
                    print (f'Batch:{k} {epoch_loss/(k)}  {epoch_acc/(k)}')  
                    torch.cuda.empty_cache()
            k=k+1
            i=i+seq_len
        epoch_loss=epoch_loss/k
        epoch_acc=epoch_acc/k
        
        if 1==0:
            lr /= 4.0
            # Freeze all the layers initially
            for param in resnet.parameters():
                param.requires_grad=False
            torch.save(resnet,'resnet')
            torch.save(resnet.state_dict(),'resnet_state_dict')
            resnet.load_state_dict(torch.load('resnet_state_dict'))
            for param_group in self.optimizer.param_groups:
                    param_group['lr']=lr  
            
        return epoch_loss,epoch_acc
    
    def plot_lrs(self, n_roll=1):
        import seaborn as sns
        ax=sns.lineplot(x=self.lrs,y=pd.Series(self.losses).rolling(n_roll).mean())
        ax.set_xscale('log')
        ax.set_ylabel('Loss')
        ax.set_xlabel('Learning Rate')

    
    def run_epochs(self,dltrain,dlvalid,n_epochs=1):
        for epoch in range(n_epochs):
            
            loss,acc=self.run_epoch(dltrain,True)
            print (f'Epoch:{epoch} Loss:{loss}')
            lossv,accv=self.run_epoch(dlvalid,mode_train=False)
            print (f'Epoch:{epoch} Loss:{loss} Accuracy:{acc} Loss:{lossv} Accuracy:{accv}')
        

In [40]:
optimizer=torch.optim.Adam(model.parameters(),lr=1e-3,betas=(0.9,0.999), weight_decay=wd)
metric_fn=accuracy_multinomial

In [41]:
n_batch=np.int(np.ceil(train_tokens.shape[1]/bptt))
n_batch

5667

In [42]:
model.freeze_embedding()

In [43]:
model.encoder.weight.requires_grad, model.decoder.weight.requires_grad

(False, False)

In [44]:
learner=Learner(model,optimizer,accuracy_multinomial,device,bptt,500,0.25)

In [45]:
model.n_inp

59972

In [ ]:
learner.run_epochs(train_tokens,valid_tokens,15)

Batch:500 4.196431321144104  0.2806391667127609
Batch:1000 4.190452457427979  0.2802335048019886
Batch:1500 4.188853911240896  0.2799085243542989
Batch:2000 4.186519870042801  0.27977053858339784
Batch:2500 4.183454562568665  0.2798749521434307
Batch:3000 4.181943955818812  0.2798991280347109
Batch:3500 4.179186931678227  0.2800296686887741
Batch:4000 4.174960896074772  0.2803190935999155
Batch:4500 4.171670879205068  0.28054444340864815
Batch:5000 4.16910322136879  0.28073800796866416
Batch:5500 4.1653584381016815  0.2810335136706179
Epoch:0 Loss:4.161546687353147
Batch:500 3.8876107177734376  0.30805880641937256
Epoch:0 Loss:4.161546687353147 Accuracy:0.281197624066717 Loss:3.8805910031381026 Accuracy:0.3073838595092962
Batch:500 4.18846431684494  0.2812952823638916
Batch:1000 4.183617264270782  0.2807462617605925
Batch:1500 4.182465254147847  0.2805121876299381
Batch:2000 4.180089966773987  0.28041875321418047
Batch:2500 4.177246946811676  0.2804681871175766
Batch:3000 4.17575251213

In [46]:
torch.save(model.state_dict(),f'{PATH}/inter/varybptt_model_state_dict_freeze')
torch.save(optimizer.state_dict(),f'{PATH}/inter/varybptt_learner_state_dict_freeze')

In [48]:
#model.load_state_dict(torch.load(f'{PATH}/inter/varybptt_model_state_dict'))
#optimizer.load_state_dict(torch.load(f'{PATH}/inter/varybptt_learner_state_dict'))

In [ ]:
learner.run_epochs(train_tokens,valid_tokens,5)

In [47]:
model.unfreeze_embedding()

In [49]:
model.encoder.weight.requires_grad, model.decoder.weight.requires_grad

(True, True)

In [50]:
learner.run_epochs(train_tokens,valid_tokens,5)

Batch:500 4.806624510765076  0.24196685341000557
Batch:1000 4.757751633644104  0.24493252439796925
Batch:1500 4.726561160087585  0.24686977541446686
Batch:2000 4.701271289825439  0.24833283469825984
Batch:2500 4.67970911693573  0.24951352741122246
Batch:3000 4.6627134453455605  0.2503829180995623
Batch:3500 4.646721647671291  0.2512773364995207
Batch:4000 4.63151394546032  0.2521417151428759
Batch:4500 4.61914976978302  0.2528052290976048
Batch:5000 4.608692124557495  0.25340674981176853
Batch:5500 4.597938516790217  0.25405117465149274
Epoch:0 Loss:4.590262610365019
Batch:500 4.204100080490113  0.2859588055610657
Epoch:0 Loss:4.590262610365019 Accuracy:0.25438765124873686 Loss:4.196222264230537 Accuracy:0.2853120703256111
Batch:500 4.470796348571778  0.26236842864751814
Batch:1000 4.461713090896606  0.2621190260797739
Batch:1500 4.457737143834432  0.26209192782640456
Batch:2000 4.4526124441623685  0.26223397482186556
Batch:2500 4.447095703887939  0.26240997207760813
Batch:3000 4.44378

In [51]:
torch.save(model.state_dict(),f'{PATH}/inter/varybptt_model_state_dict')
torch.save(optimizer.state_dict(),f'{PATH}/inter/varybptt_learner_state_dict')

In [52]:
learner.run_epochs(train_tokens,valid_tokens,4)

Batch:500 4.272457369804382  0.27471615970134733
Batch:1000 4.267559949874878  0.2740515992343426
Batch:1500 4.267114808082581  0.273838185886542
Batch:2000 4.266339130401612  0.27369468961656096
Batch:2500 4.264564046478272  0.2736269864797592
Batch:3000 4.264817505757014  0.27352512232462567
Batch:3500 4.263663566112518  0.27356928267223496
Batch:4000 4.2613649269938465  0.27369629619270563
Batch:4500 4.2601746790674  0.2737410924302207
Batch:5000 4.259788099336624  0.273805964243412
Batch:5500 4.258415932611985  0.27396675740317866
Epoch:0 Loss:4.256667076612103
Batch:500 3.9689039225578306  0.3013489162325859
Epoch:0 Loss:4.256667076612103 Accuracy:0.273989359056968 Loss:3.961688128004424 Accuracy:0.30059371971817866
Batch:500 4.253802610397339  0.27625672483444214
Batch:1000 4.250454862594604  0.27541374777257444
Batch:1500 4.250013441085815  0.27510657292604446
Batch:2000 4.249407567024231  0.2749712665230036
Batch:2500 4.247304359817505  0.27495967178344727
Batch:3000 4.24719579

In [53]:
torch.save(model.state_dict(),f'{PATH}/inter/varybptt_model_state_dict')
torch.save(optimizer.state_dict(),f'{PATH}/inter/varybptt_learner_state_dict')

In [54]:
learner.run_epochs(train_tokens,valid_tokens,2)

Batch:500 4.215587013244629  0.2790443264245987
Batch:1000 4.212339537620545  0.2783490325063467
Batch:1500 4.21223117129008  0.2779750633140405
Batch:2000 4.212278420805931  0.2777671938613057
Batch:2500 4.2109540965080265  0.27770000673532486
Batch:3000 4.211227813800176  0.2775996452718973
Batch:3500 4.210249499525343  0.27761185379964964
Batch:4000 4.20857752674818  0.2777071903422475
Batch:4500 4.207921216752794  0.27771874876817065
Batch:5000 4.208143178653717  0.2777416648209095
Batch:5500 4.207130738258362  0.27786863873221657
Epoch:0 Loss:4.205581469679631
Batch:500 3.912629920005798  0.305733531832695
Epoch:0 Loss:4.205581469679631 Accuracy:0.2779049221745413 Loss:3.905625071822171 Accuracy:0.3050169282172475
Batch:500 4.207696530342102  0.27951427340507506
Batch:1000 4.2041611847877505  0.27889167445898055
Batch:1500 4.203369742393494  0.2785125058889389
Batch:2000 4.202742716908455  0.27842603901028634
Batch:2500 4.201797800922394  0.2782968729197979
Batch:3000 4.2017882812

In [55]:
np.exp(3.9), np.exp(3.89)

(49.40244910553017, 48.91088652373189)

In [2]:
import numpy as np

In [3]:
np.exp(4.19)

66.02279096040995

In [56]:
torch.save(model.state_dict(),f'{PATH}/inter/varybptt_model_state_dict')
torch.save(optimizer.state_dict(),f'{PATH}/inter/varybptt_learner_state_dict')

In [57]:
torch.save (model,f'{PATH}/inter/varybptt_model_awd_lstm')


/home/kirana/anaconda3/lib/python3.7/site-packages/torch/serialization.py:256: UserWarning: Couldn't retrieve source code for container of type language_model. It won't be checked for correctness upon loading.
  "type " + obj.__name__ + ". It won't be checked "


In [58]:
torch.save (optimizer,f'{PATH}/inter/varybptt_optimizer_awd_lstm')

In [59]:
torch.save (learner,f'{PATH}/inter/varybptt_learner_awd_lstm')

In [80]:
if 1==0:
    learner.lr_find(1e-4,1e-1,valid_tokens,n_batch)
    learner.plot_lrs(50)
    len(learner.lrs)
    len(learner.losses)

Batch:500 7.944759424209595  0.03532285663112998
Batch:1000 7.877773783683777  0.03720142808556557
Batch:1500 7.802010853131613  0.03968857092410326
Batch:2000 7.722838351964951  0.04160571377538145
Batch:2500 7.658665308570862  0.043098285208642485


## Transfer Learning to predict RNN